# Introduction

Fine particulate matter (PM{2.5}) is an ambient air pollutant for which there is strong evidence that it is harmful to human health. In the United States, the Environmental Protection Agency (EPA) is tasked with setting national ambient air quality standards for fine PM and for tracking the emissions of this pollutant into the atmosphere. Approximatly every 3 years, the EPA releases its database on emissions of PM{2.5}. This database is known as the National Emissions Inventory (NEI). Visit the [EPA National Emissions Inventory web site][1] for more information about the NEI.

For each year and for each type of PM source, the NEI records how many tons of PM{2.5} were emitted from that source over the course of the entire year. The data for this report are from 1999, 2002, 2005, and 2008 



#Plotting

The current report contains the plots of data associated with the following questions:

1. Have total emissions from PM{2.5} decreased in the United States from 1999 to 2008? See [plot1][2].  
2.Have total emissions from PM{2.5} decreased in the Baltimore City, Maryland from 1999 to 2008? See [plot2][3].
3. Of the four types of sources indicated by the =type= (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999-2008 for Baltimore City? Which have seen increases in emissions from 1999-2008? See [plot3][4].
4. Across the United States, how have emissions from coal combustion-related sources changed from 1999-2008? See [plot4][5].
5. How have emissions from motor vehicle sources changed from 1999-2008 in Baltimore City? See [plot5][6].
6. Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in Los Angeles County, California. Which city has seen greater changes over time in motor vehicle emissions? See [plot6][7].

[1]: https://www.epa.gov/air-emissions-inventories
[2]: https://github.com/Const4nce/ExpDataAnalysis_Plotting2/blob/master/plot1.png
[3]: https://github.com/Const4nce/ExpDataAnalysis_Plotting2/blob/master/plot2.png
[4]: https://github.com/Const4nce/ExpDataAnalysis_Plotting2/blob/master/plot3.png
[5]: https://github.com/Const4nce/ExpDataAnalysis_Plotting2/blob/master/plot4.png
[6]: https://github.com/Const4nce/ExpDataAnalysis_Plotting2/blob/master/plot5.png
[7]: https://github.com/Const4nce/ExpDataAnalysis_Plotting2/blob/master/plot6.png

